// The PaperFold sequence (also known as the dragon curve sequence) is an infinite
// sequence of 0s and 1s generated by repeatedly inserting an alternating pattern.
// Each iteration of the sequence is formed by: previous + [1] + reverse(NOT(previous))
// This creates: 1 -> 1,1,0 -> 1,1,0,1,1,0,0 -> 1,1,0,1,1,0,0,1,1,1,0,0,1,0,0 -> ...

package main

// PaperFold returns a function that generates successive values of the paper folding sequence
func PaperFold() func() int {
	// TODO: Implement the paper fold generator
	return nil
}