// Ludic numbers
// 
// The ludic numbers are generated by a sieving process:
// 1. Start with natural numbers from 2
// 2. 1 is the first ludic number
// 3. Take the first element from the array as a ludic number
// 4. Remove every nth indexed element (where n is that element)
// 5. Repeat until we have enough ludic numbers
// 
// Given n, return the sum of the first n ludic numbers.
// 
// Examples:
// sumLudic(1)  -> 1
// sumLudic(10) -> 107
// sumLudic(25) -> 1100

function sumLudic(n) {
  // function body
}