/*
The ludic numbers are a set of numbers related to prime numbers, as they are generated by sieving.

Generation of ludic numbers:
First take the natural numbers starting from 2.
1 is the first ludic number.

Take the first element from the array and mark it as ludic.
Remove every kth indexed element (where k is that first element).
Repeat until you have enough ludic numbers.

For example:
- Start: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, ...]
- Take 2: Ludic = {1, 2}. Remove indices 0, 2, 4, 6, 8, ...
  Result: [3, 5, 7, 9, 11, ...]
- Take 3: Ludic = {1, 2, 3}. Remove indices 0, 3, 6, 9, ...
  Result: [5, 7, 11, 13, ...]

Write a function to return an integer: the sum of the first n ludic numbers.
You can assume that 1 ≤ n ≤ 10000.
*/

function sumLudic(n) {
  // stub
}